service: express-rds

plugins:
  - serverless-fargate

custom:
  rds:
    database: demoRDSMysql1
    user: ${env:DB_USER}
    password: ${env:DB_PASSWORD}

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
  ecr:
    images:
      rds-express:
        path: ./app-express/
        file: Dockerfile

fargate:
  clusterName: express-fargate-cluster
  containerInsights: true
  memory: '4 GB'
  cpu: 2048
  architecture: X86_64
  vpc:
    assignPublicIp: true
    securityGroupIds:
      - Fn::GetAtt: [SecurityGroup0, GroupId]
    subnetIds:
      - Fn::GetAtt: [Subnet1, SubnetId]
  tasks:
    rds-express-fargate-task:
      name: rds-express-fargate-task
      image: rds-express
      memory: '2 GB'
      cpu: 1024
      vpc:
        securityGroupIds:
          - Fn::GetAtt: [SecurityGroup0, GroupId]
        subnetIds:
          - Fn::GetAtt: [Subnet1, SubnetId]
        assignPublicIp: true
      service:
        desiredCount: 1
        maximumPercent: 200
      cloudFormationResource:
        container:
          PortMappings:
            - ContainerPort: 8080
              HostPort: 8080

resources:
  Resources:
    Express-VPC:
      Type: AWS::EC2:VPC
      Properties: 
        CidrBlock: 10.0.0.0/24

    InternetGateway:
      Type: AWS::EC2::InternetGateway

    AttachGateway:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties:
        VpcId: 
          Fn::GetAtt: [Express-VPC, VpcId]
        InternetGatewayId:
          Fn::GetAtt: [InternetGateway, InternetGatewayId]

    Subnet1:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId:
          Fn::GetAtt: [Express-VPC, VpcId]
        CidrBlock: 10.0.0.0/28

    Subnet2:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId:
          Fn::GetAtt: [Express-VPC, VpcId]
        CidrBlock: 10.0.0.16/28

    SecurityGroup0:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: My Security Group for express app
        VpcId:
          Fn::GetAtt: [Express-VPC, VpcId]

    SecurityGroup1:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: My Security Group for RDS
        VpcId:
          Fn::GetAtt: [Express-VPC, VpcId]
        SecurityGroupIngress:
          - CidrIp:
              Fn::GetAtt: [Subnet1, CidrBlock]
            IpProtocol: tcp
            FromPort: 3306
            ToPort: 3306

    PublicRouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId:
          Fn::GetAtt: [Express-VPC, VpcId]

    PrivateRouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId:
          Fn::GetAtt: [Express-VPC, VpcId]

    RouteToInternetGateway:
      Type: AWS::EC2::Route
      DependsOn: AttachGateway
      Properties:
        RouteTableId: !Ref PublicRouteTable
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId: !Ref InternetGateway

    AssociatePublicSubnetRouteTable:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        SubnetId: !Ref Subnet1
        RouteTableId: !Ref PublicRouteTable

    AssociatePrivateSubnetRouteTable:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        SubnetId: !Ref Subnet2
        RouteTableId: !Ref PrivateRouteTable

    DemoRDSMySQL:
      Type: AWS::RDS::DBInstance
      Properties:
        DBName: ${self:custom.rds.database}
        MasterUsername: ${self:custom.rds.user}
        MasterUserPassword: ${self:custom.rds.password}
        Engine: MySQL
        AllocatedStorage: 5
        DBInstanceClass: db.t2.small
        PubliclyAccessible: false
        VPCSecurityGroups:
          - Fn::GetAtt: [SecurityGroup1, GroupId]
        DBSubnetGroupName: !Ref DemoDBSubnetGroup

    DemoDBSubnetGroup:
      Type: AWS::RDS::DBSubnetGroup
      Properties:
        DBSubnetGroupDescription: Subnet Group for RDS Instance
        SubnetIds:
          - !Ref Subnet2