service: express-rds

plugins:
  - serverless-fargate

custom:
  rds:
    database: demoRDSMysql1
    user: ${env:DB_USER}
    password: ${env:DB_PASSWORD}
  vpc:
    defaultVpcId: vpc-0192d315eced25399
    defaultSecurityGroup: sg-02f592e8908c5e3de
    defaultSubnetId: subnet-0144263fc47c9300e
    defaultCidr: 172.31.16.0/20

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
  # deploymentBucket:
  #   name: serverless-deployment-bucket-backend
  ecr:
    images:
      rds-express:
        path: ./app-express/
        file: Dockerfile

fargate:
  clusterName: express-fargate-cluster
  containerInsights: true
  memory: '4 GB'
  cpu: 2048
  architecture: X86_64
  vpc:
    assignPublicIp: true
    securityGroupIds:
      - ${self:custom.vpc.defaultSecurityGroup}
    subnetIds:
      - ${self:custom.vpc.defaultSubnetId}
  tasks:
    rds-express-fargate-task:
      name: rds-express-fargate-task
      image: rds-express
      memory: '2 GB'
      cpu: 1024
      vpc:
        securityGroupIds:
          - Fn::GetAtt: [SecurityGroup0, GroupId]
        subnetIds:
          - ${self:custom.vpc.defaultSubnetId}
        assignPublicIp: true
      service:
        desiredCount: 1
        maximumPercent: 200
      cloudFormationResource:
        container:
          PortMappings:
            - ContainerPort: 8080
              HostPort: 8080
      environment:
        DB_USER: ${self:custom.rds.user}
        DB_PASSWORD: ${self:custom.rds.password}
        DB_NAME: ${self:custom.rds.database}
        DB_HOST:
          Fn::GetAtt: [DemoRDSMySQL, Endpoint.Address]
        DB_PORT:
          Fn::GetAtt: [DemoRDSMySQL, Endpoint.Port]

resources:
  Resources:
    SecurityGroup0:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: My Security Group for Express App on Fargate
        VpcId: ${self:custom.vpc.defaultVpcId}
        SecurityGroupIngress:
          - CidrIp: 0.0.0.0/0
            IpProtocol: -1

    SecurityGroup1:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: My Security Group for RDS
        VpcId: ${self:custom.vpc.defaultVpcId}
        SecurityGroupIngress:
          # - CidrIp: ${self:custom.vpc.defaultCidr}
          - SourceSecurityGroupId: !Ref SecurityGroup0
            IpProtocol: tcp
            FromPort: 3306
            ToPort: 3306

    DemoRDSMySQL:
      Type: AWS::RDS::DBInstance
      Properties:
        DBName: ${self:custom.rds.database}
        MasterUsername: ${self:custom.rds.user}
        MasterUserPassword: ${self:custom.rds.password}
        Engine: MySQL
        AllocatedStorage: 5
        DBInstanceClass: db.t2.small
        PubliclyAccessible: false
        VPCSecurityGroups:
          - Fn::GetAtt: [SecurityGroup1, GroupId]
